import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AccordionModule, AlertModule,
         ButtonsModule, CarouselModule, CollapseModule,
         BsDropdownModule,
         DateFormatter,
         DatePickerComponent,
         DatepickerConfig,
         DatepickerModule,
         DayPickerComponent,
         MonthPickerComponent,
         YearPickerComponent,
         BsDatepickerModule,
        //  BsDatepickerConfig,
         BsDaterangepickerConfig,
         BsLocaleService,
         BsDaterangepickerDirective,
         BsDatepickerDirective,
         ModalModule,
         PaginationModule,
         PopoverModule,
         ProgressbarModule,
         RatingModule,
         SortableModule,
         TabsModule,
         TimepickerModule,
         TooltipModule,
         TypeaheadModule } from 'ngx-bootstrap';


@NgModule({
    declarations: [],
    imports: [
        CommonModule,
        AccordionModule,
        AlertModule,
        ButtonsModule,
        CarouselModule,
        CollapseModule,
        BsDropdownModule,
        BsDatepickerModule,
        // BsDatepickerConfig,
        DatepickerModule.forRoot(),
        ModalModule,
        PaginationModule,
        PopoverModule,
        ProgressbarModule,
        RatingModule,
        SortableModule,
        TabsModule,
        TimepickerModule,
        TooltipModule,
        TypeaheadModule.forRoot()
     ],
    exports: [
        AccordionModule,
        AlertModule,
        ButtonsModule,
        CarouselModule,
        CollapseModule,
        BsDropdownModule,
        BsDatepickerModule,
        // BsDatepickerConfig,
        DatepickerModule,
        ModalModule,
        PaginationModule,
        PopoverModule,
        ProgressbarModule,
        RatingModule,
        SortableModule,
        TabsModule,
        TimepickerModule,
        TooltipModule,
        TypeaheadModule
    ],
    providers: [],
})
export class NgXBootstrapModule {
}
